### ISSUE TITLE
UD Importer: allow URL as input in addition to file

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/service-user-dataset-import#12]
adjust the importer API to take an URL as an option, instead of a file.  read the url to dereference into a file.

**Comment by Foxcapades** [comment]
This service alone has no queue.  IDK if there is another queue being talked about that happens before this service though

**Comment by danicahelb** [comment]
FYI I'm moving this ticket to b59. We want DIY to be publicly released in b59, but made available on the QA site in b58.
