### ISSUE TITLE
Display file name metadata for users importing Gene List files

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/service-user-dataset-import#28]
## User Story
Currently, when a user imports a GeneList dataset, there is no way for a user to know the original file name or URL it was uploaded from. As a user, it may be useful to have that metadata retained by the service and displayed when viewing user datasets (as a column?).

## Technical Details
This would involve updates to:
1. Gene list to store file name metadata in new or existing field
2. API to list datasets returns file name
3. UI changes to show file name

Note: The work for this issue spans multiple repositories and includes front-end work as well. Creating it in UDIS for now.

**Comment by aurreco-uga** [comment]
this si fixed in vdi
