### ISSUE TITLE
WDK UDs uploaded through this service have extra quotation marks around the name, summary, and description fields

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/service-user-dataset-import#30]

**Comment by dmgaldi** [comment]
PR to address this: https://github.com/VEuPathDB/util-user-dataset-handler-server/pull/26#pullrequestreview-1060840980

**Comment by SheenaTomko** [comment]
This looks great @dmgaldi. Should I mark the status for this as "Done" and close the ticket?

**Comment by dmgaldi** [comment]
Great! Yeah, I'll go ahead and close it now
